### ISSUE TITLE
３つのモデル・コントローラー作成

### ISSUE THREAD

**Issue by TanoueDaisuke** [TanoueDaisuke/laravel-insta#12]
- Post, Like, Commentの３つ
- リレーションがある場合はhasManyも設定する

**Comment by taicihi** [comment]
Post, Like, Commentモデル作成済み

**Comment by taicihi** [comment]
Post, Like, Commentのモデル設定ファイルの
関連しているテーブルの設定済み。

**Comment by taicihi** [comment]
シーダーやります！
Database/Seeder フォルダの位置
UserTableSeeder ファイル名
